const $=s=>document.querySelector(s);const KEY='ct_ai_v1';let pending=null;
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{goal:{calories:2000,protein:120},meals:[],profile:null};
function today(){return new Date().toISOString().slice(0,10)}function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function dayMeals(){return state.meals.filter(m=>m.date===today())}function render(){const ms=dayMeals(),cal=Math.round(ms.reduce((a,m)=>a+m.calories,0)),pro=Math.round(ms.reduce((a,m)=>a+m.protein,0));$('#calNow').textContent=cal;$('#proNow').textContent=pro;$('#calGoal').textContent=state.goal.calories;$('#proGoal').textContent=state.goal.protein;const cp=Math.min(100,Math.round(cal/state.goal.calories*100)||0),pp=Math.min(100,Math.round(pro/state.goal.protein*100)||0);$('#pct').textContent=cp+'%';$('#calBar').style.width=cp+'%';$('#proBar').style.width=pp+'%';$('#remaining').textContent=cal<=state.goal.calories?`Te quedan ${state.goal.calories-cal} kcal hoy`:`Superaste el objetivo por ${cal-state.goal.calories} kcal`;$('#meals').innerHTML=ms.length?ms.map(m=>`<div class="meal"><div><b>${esc(m.type)}</b><p>${esc(m.description)}</p></div><div class="macro"><b>${Math.round(m.calories)} kcal</b><span>${Math.round(m.protein)} g proteína</span></div></div>`).join(''):'<div class="empty">Todavía no registraste comidas hoy.</div>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#analyzeBtn').onclick=async()=>{const text=$('#mealText').value.trim();if(!text)return;const b=$('#analyzeBtn');b.disabled=true;$('#status').className='';$('#status').textContent='Analizando tu comida…';try{const r=await fetch('/api/analyze-meal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo analizar');pending=d;showResult(d);$('#status').textContent=''}catch(e){$('#status').className='error';$('#status').textContent=e.message+' — Para usar el análisis con IA, ejecutá CalorieTrack con su servidor.'}finally{b.disabled=false}}
function showResult(d){$('#result').classList.remove('hidden');$('#resultCal').textContent=Math.round(d.total_calories);$('#resultPro').textContent=Math.round(d.total_protein_g);$('#items').innerHTML=d.items.map(i=>`<div class="food-item"><div><b>${esc(i.name)}</b><small>${esc(i.amount_text)}${i.preparation?' · '+esc(i.preparation):''} ${i.estimated?'<span class="estimated">· estimado</span>':''}</small></div><div class="food-macro"><b>${Math.round(i.calories)} kcal</b><small>${Math.round(i.protein_g)} g proteína</small></div></div>`).join('');$('#note').textContent=d.note||'Los valores son estimaciones nutricionales y pueden variar según marca, receta y porción.';$('#result').scrollIntoView({behavior:'smooth',block:'center'})}
$('#saveBtn').onclick=()=>{if(!pending)return;state.meals.push({id:Date.now(),date:today(),type:$('#mealType').value,description:$('#mealText').value.trim(),calories:pending.total_calories,protein:pending.total_protein_g,items:pending.items});save();pending=null;$('#result').classList.add('hidden');$('#mealText').value='';render()};
$('#clearBtn').onclick=()=>{if(confirm('¿Eliminar las comidas registradas hoy?')){state.meals=state.meals.filter(m=>m.date!==today());save();render()}};
$('#goalBtn').onclick=()=>$('#goalModal').classList.remove('hidden');$('#closeGoal').onclick=()=>$('#goalModal').classList.add('hidden');
$('#goalForm').onsubmit=e=>{e.preventDefault();const w=+$('#weight').value,h=+$('#height').value,a=+$('#age').value,sex=$('#sex').value,act=+$('#activity').value,type=$('#goalType').value;const bmr=10*w+6.25*h-5*a+(sex==='male'?5:-161),tdee=bmr*act,adj=type==='deficit'?-400:type==='surplus'?300:0,cal=Math.round(tdee+adj),protein=Math.round(w*(type==='surplus'?1.8:type==='deficit'?1.8:1.6));state.profile={w,h,a,sex,act,type};state.goal={calories:cal,protein};save();$('#goalModal').classList.add('hidden');render()};
if(state.profile){$('#weight').value=state.profile.w;$('#height').value=state.profile.h;$('#age').value=state.profile.a;$('#sex').value=state.profile.sex;$('#activity').value=state.profile.act;$('#goalType').value=state.profile.type}
$('#whatsappBtn').onclick=e=>{if($('#whatsappBtn').getAttribute('href')==='#'){e.preventDefault();alert('Falta configurar el enlace de tu canal de WhatsApp.')}};render();
